/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RankingRouteImport } from './routes/ranking'
import { Route as PosisiRouteImport } from './routes/posisi'
import { Route as LiveRouteImport } from './routes/live'
import { Route as DaftarRouteImport } from './routes/daftar'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VmixNowreadingRouteImport } from './routes/vmix.nowreading'
import { Route as VmixLeaderboardRouteImport } from './routes/vmix.leaderboard'
import { Route as AuthenticatedOperatorRouteImport } from './routes/_authenticated/operator'
import { Route as AuthenticatedInspekturRouteImport } from './routes/_authenticated/inspektur'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as ApiPublicBootstrapAdminRouteImport } from './routes/api/public/bootstrap-admin'
import { Route as ApiPublicLiveJsonRouteImport } from './routes/api/public/live.json'

const RankingRoute = RankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => rootRouteImport,
} as any)
const PosisiRoute = PosisiRouteImport.update({
  id: '/posisi',
  path: '/posisi',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const DaftarRoute = DaftarRouteImport.update({
  id: '/daftar',
  path: '/daftar',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VmixNowreadingRoute = VmixNowreadingRouteImport.update({
  id: '/vmix/nowreading',
  path: '/vmix/nowreading',
  getParentRoute: () => rootRouteImport,
} as any)
const VmixLeaderboardRoute = VmixLeaderboardRouteImport.update({
  id: '/vmix/leaderboard',
  path: '/vmix/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOperatorRoute = AuthenticatedOperatorRouteImport.update({
  id: '/operator',
  path: '/operator',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInspekturRoute = AuthenticatedInspekturRouteImport.update({
  id: '/inspektur',
  path: '/inspektur',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicBootstrapAdminRoute = ApiPublicBootstrapAdminRouteImport.update({
  id: '/api/public/bootstrap-admin',
  path: '/api/public/bootstrap-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicLiveJsonRoute = ApiPublicLiveJsonRouteImport.update({
  id: '/api/public/live/json',
  path: '/api/public/live/json',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/daftar': typeof DaftarRoute
  '/live': typeof LiveRoute
  '/posisi': typeof PosisiRoute
  '/ranking': typeof RankingRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/inspektur': typeof AuthenticatedInspekturRoute
  '/operator': typeof AuthenticatedOperatorRoute
  '/vmix/leaderboard': typeof VmixLeaderboardRoute
  '/vmix/nowreading': typeof VmixNowreadingRoute
  '/api/public/bootstrap-admin': typeof ApiPublicBootstrapAdminRoute
  '/api/public/live/json': typeof ApiPublicLiveJsonRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/daftar': typeof DaftarRoute
  '/live': typeof LiveRoute
  '/posisi': typeof PosisiRoute
  '/ranking': typeof RankingRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/inspektur': typeof AuthenticatedInspekturRoute
  '/operator': typeof AuthenticatedOperatorRoute
  '/vmix/leaderboard': typeof VmixLeaderboardRoute
  '/vmix/nowreading': typeof VmixNowreadingRoute
  '/api/public/bootstrap-admin': typeof ApiPublicBootstrapAdminRoute
  '/api/public/live/json': typeof ApiPublicLiveJsonRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/daftar': typeof DaftarRoute
  '/live': typeof LiveRoute
  '/posisi': typeof PosisiRoute
  '/ranking': typeof RankingRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/inspektur': typeof AuthenticatedInspekturRoute
  '/_authenticated/operator': typeof AuthenticatedOperatorRoute
  '/vmix/leaderboard': typeof VmixLeaderboardRoute
  '/vmix/nowreading': typeof VmixNowreadingRoute
  '/api/public/bootstrap-admin': typeof ApiPublicBootstrapAdminRoute
  '/api/public/live/json': typeof ApiPublicLiveJsonRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/daftar'
    | '/live'
    | '/posisi'
    | '/ranking'
    | '/dashboard'
    | '/inspektur'
    | '/operator'
    | '/vmix/leaderboard'
    | '/vmix/nowreading'
    | '/api/public/bootstrap-admin'
    | '/api/public/live/json'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/daftar'
    | '/live'
    | '/posisi'
    | '/ranking'
    | '/dashboard'
    | '/inspektur'
    | '/operator'
    | '/vmix/leaderboard'
    | '/vmix/nowreading'
    | '/api/public/bootstrap-admin'
    | '/api/public/live/json'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/daftar'
    | '/live'
    | '/posisi'
    | '/ranking'
    | '/_authenticated/dashboard'
    | '/_authenticated/inspektur'
    | '/_authenticated/operator'
    | '/vmix/leaderboard'
    | '/vmix/nowreading'
    | '/api/public/bootstrap-admin'
    | '/api/public/live/json'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  DaftarRoute: typeof DaftarRoute
  LiveRoute: typeof LiveRoute
  PosisiRoute: typeof PosisiRoute
  RankingRoute: typeof RankingRoute
  VmixLeaderboardRoute: typeof VmixLeaderboardRoute
  VmixNowreadingRoute: typeof VmixNowreadingRoute
  ApiPublicBootstrapAdminRoute: typeof ApiPublicBootstrapAdminRoute
  ApiPublicLiveJsonRoute: typeof ApiPublicLiveJsonRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ranking': {
      id: '/ranking'
      path: '/ranking'
      fullPath: '/ranking'
      preLoaderRoute: typeof RankingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posisi': {
      id: '/posisi'
      path: '/posisi'
      fullPath: '/posisi'
      preLoaderRoute: typeof PosisiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daftar': {
      id: '/daftar'
      path: '/daftar'
      fullPath: '/daftar'
      preLoaderRoute: typeof DaftarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vmix/nowreading': {
      id: '/vmix/nowreading'
      path: '/vmix/nowreading'
      fullPath: '/vmix/nowreading'
      preLoaderRoute: typeof VmixNowreadingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vmix/leaderboard': {
      id: '/vmix/leaderboard'
      path: '/vmix/leaderboard'
      fullPath: '/vmix/leaderboard'
      preLoaderRoute: typeof VmixLeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/operator': {
      id: '/_authenticated/operator'
      path: '/operator'
      fullPath: '/operator'
      preLoaderRoute: typeof AuthenticatedOperatorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inspektur': {
      id: '/_authenticated/inspektur'
      path: '/inspektur'
      fullPath: '/inspektur'
      preLoaderRoute: typeof AuthenticatedInspekturRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/bootstrap-admin': {
      id: '/api/public/bootstrap-admin'
      path: '/api/public/bootstrap-admin'
      fullPath: '/api/public/bootstrap-admin'
      preLoaderRoute: typeof ApiPublicBootstrapAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/live/json': {
      id: '/api/public/live/json'
      path: '/api/public/live/json'
      fullPath: '/api/public/live/json'
      preLoaderRoute: typeof ApiPublicLiveJsonRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedInspekturRoute: typeof AuthenticatedInspekturRoute
  AuthenticatedOperatorRoute: typeof AuthenticatedOperatorRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedInspekturRoute: AuthenticatedInspekturRoute,
  AuthenticatedOperatorRoute: AuthenticatedOperatorRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  DaftarRoute: DaftarRoute,
  LiveRoute: LiveRoute,
  PosisiRoute: PosisiRoute,
  RankingRoute: RankingRoute,
  VmixLeaderboardRoute: VmixLeaderboardRoute,
  VmixNowreadingRoute: VmixNowreadingRoute,
  ApiPublicBootstrapAdminRoute: ApiPublicBootstrapAdminRoute,
  ApiPublicLiveJsonRoute: ApiPublicLiveJsonRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
