/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RankingRouteImport } from './routes/ranking'
import { Route as PosisiRouteImport } from './routes/posisi'
import { Route as LiveRouteImport } from './routes/live'
import { Route as KeberatanRouteImport } from './routes/keberatan'
import { Route as DaftarRouteImport } from './routes/daftar'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VmixVarwarningRouteImport } from './routes/vmix.varwarning'
import { Route as VmixSkorRouteImport } from './routes/vmix.skor'
import { Route as VmixNowreadingRouteImport } from './routes/vmix.nowreading'
import { Route as VmixLeaderboardRouteImport } from './routes/vmix.leaderboard'
import { Route as AuthenticatedVmixRouteImport } from './routes/_authenticated/vmix'
import { Route as AuthenticatedViewerRouteImport } from './routes/_authenticated/viewer'
import { Route as AuthenticatedSkorRouteImport } from './routes/_authenticated/skor'
import { Route as AuthenticatedOperatorRouteImport } from './routes/_authenticated/operator'
import { Route as AuthenticatedInspekturVarRouteImport } from './routes/_authenticated/inspektur-var'
import { Route as AuthenticatedInspekturRouteImport } from './routes/_authenticated/inspektur'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as ApiPublicSkorDotxmlRouteImport } from './routes/api/public/skor[.]xml'
import { Route as ApiPublicSkorDotjsonRouteImport } from './routes/api/public/skor[.]json'
import { Route as ApiPublicNowreadingDotxmlRouteImport } from './routes/api/public/nowreading[.]xml'
import { Route as ApiPublicLiveDotjsonRouteImport } from './routes/api/public/live[.]json'
import { Route as ApiPublicKeberatanRouteImport } from './routes/api/public/keberatan'
import { Route as ApiPublicBootstrapJuriDummyRouteImport } from './routes/api/public/bootstrap-juri-dummy'
import { Route as ApiPublicBootstrapAdminRouteImport } from './routes/api/public/bootstrap-admin'
import { Route as ApiPublicVmixSkorDothtmlRouteImport } from './routes/api/public/vmix/skor[.]html'
import { Route as ApiPublicVmixNowreadingDothtmlRouteImport } from './routes/api/public/vmix/nowreading[.]html'
import { Route as ApiPublicVmixLeaderboardDothtmlRouteImport } from './routes/api/public/vmix/leaderboard[.]html'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingRoute = RankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => rootRouteImport,
} as any)
const PosisiRoute = PosisiRouteImport.update({
  id: '/posisi',
  path: '/posisi',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const KeberatanRoute = KeberatanRouteImport.update({
  id: '/keberatan',
  path: '/keberatan',
  getParentRoute: () => rootRouteImport,
} as any)
const DaftarRoute = DaftarRouteImport.update({
  id: '/daftar',
  path: '/daftar',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VmixVarwarningRoute = VmixVarwarningRouteImport.update({
  id: '/vmix/varwarning',
  path: '/vmix/varwarning',
  getParentRoute: () => rootRouteImport,
} as any)
const VmixSkorRoute = VmixSkorRouteImport.update({
  id: '/vmix/skor',
  path: '/vmix/skor',
  getParentRoute: () => rootRouteImport,
} as any)
const VmixNowreadingRoute = VmixNowreadingRouteImport.update({
  id: '/vmix/nowreading',
  path: '/vmix/nowreading',
  getParentRoute: () => rootRouteImport,
} as any)
const VmixLeaderboardRoute = VmixLeaderboardRouteImport.update({
  id: '/vmix/leaderboard',
  path: '/vmix/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedVmixRoute = AuthenticatedVmixRouteImport.update({
  id: '/vmix',
  path: '/vmix',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedViewerRoute = AuthenticatedViewerRouteImport.update({
  id: '/viewer',
  path: '/viewer',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSkorRoute = AuthenticatedSkorRouteImport.update({
  id: '/skor',
  path: '/skor',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOperatorRoute = AuthenticatedOperatorRouteImport.update({
  id: '/operator',
  path: '/operator',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInspekturVarRoute =
  AuthenticatedInspekturVarRouteImport.update({
    id: '/inspektur-var',
    path: '/inspektur-var',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInspekturRoute = AuthenticatedInspekturRouteImport.update({
  id: '/inspektur',
  path: '/inspektur',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicSkorDotxmlRoute = ApiPublicSkorDotxmlRouteImport.update({
  id: '/api/public/skor.xml',
  path: '/api/public/skor.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSkorDotjsonRoute = ApiPublicSkorDotjsonRouteImport.update({
  id: '/api/public/skor.json',
  path: '/api/public/skor.json',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicNowreadingDotxmlRoute =
  ApiPublicNowreadingDotxmlRouteImport.update({
    id: '/api/public/nowreading.xml',
    path: '/api/public/nowreading.xml',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicLiveDotjsonRoute = ApiPublicLiveDotjsonRouteImport.update({
  id: '/api/public/live.json',
  path: '/api/public/live.json',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicKeberatanRoute = ApiPublicKeberatanRouteImport.update({
  id: '/api/public/keberatan',
  path: '/api/public/keberatan',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBootstrapJuriDummyRoute =
  ApiPublicBootstrapJuriDummyRouteImport.update({
    id: '/api/public/bootstrap-juri-dummy',
    path: '/api/public/bootstrap-juri-dummy',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicBootstrapAdminRoute = ApiPublicBootstrapAdminRouteImport.update({
  id: '/api/public/bootstrap-admin',
  path: '/api/public/bootstrap-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicVmixSkorDothtmlRoute =
  ApiPublicVmixSkorDothtmlRouteImport.update({
    id: '/api/public/vmix/skor.html',
    path: '/api/public/vmix/skor.html',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicVmixNowreadingDothtmlRoute =
  ApiPublicVmixNowreadingDothtmlRouteImport.update({
    id: '/api/public/vmix/nowreading.html',
    path: '/api/public/vmix/nowreading.html',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicVmixLeaderboardDothtmlRoute =
  ApiPublicVmixLeaderboardDothtmlRouteImport.update({
    id: '/api/public/vmix/leaderboard.html',
    path: '/api/public/vmix/leaderboard.html',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/daftar': typeof DaftarRoute
  '/keberatan': typeof KeberatanRoute
  '/live': typeof LiveRoute
  '/posisi': typeof PosisiRoute
  '/ranking': typeof RankingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/inspektur': typeof AuthenticatedInspekturRoute
  '/inspektur-var': typeof AuthenticatedInspekturVarRoute
  '/operator': typeof AuthenticatedOperatorRoute
  '/skor': typeof AuthenticatedSkorRoute
  '/viewer': typeof AuthenticatedViewerRoute
  '/vmix': typeof AuthenticatedVmixRoute
  '/vmix/leaderboard': typeof VmixLeaderboardRoute
  '/vmix/nowreading': typeof VmixNowreadingRoute
  '/vmix/skor': typeof VmixSkorRoute
  '/vmix/varwarning': typeof VmixVarwarningRoute
  '/api/public/bootstrap-admin': typeof ApiPublicBootstrapAdminRoute
  '/api/public/bootstrap-juri-dummy': typeof ApiPublicBootstrapJuriDummyRoute
  '/api/public/keberatan': typeof ApiPublicKeberatanRoute
  '/api/public/live.json': typeof ApiPublicLiveDotjsonRoute
  '/api/public/nowreading.xml': typeof ApiPublicNowreadingDotxmlRoute
  '/api/public/skor.json': typeof ApiPublicSkorDotjsonRoute
  '/api/public/skor.xml': typeof ApiPublicSkorDotxmlRoute
  '/api/public/vmix/leaderboard.html': typeof ApiPublicVmixLeaderboardDothtmlRoute
  '/api/public/vmix/nowreading.html': typeof ApiPublicVmixNowreadingDothtmlRoute
  '/api/public/vmix/skor.html': typeof ApiPublicVmixSkorDothtmlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/daftar': typeof DaftarRoute
  '/keberatan': typeof KeberatanRoute
  '/live': typeof LiveRoute
  '/posisi': typeof PosisiRoute
  '/ranking': typeof RankingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/inspektur': typeof AuthenticatedInspekturRoute
  '/inspektur-var': typeof AuthenticatedInspekturVarRoute
  '/operator': typeof AuthenticatedOperatorRoute
  '/skor': typeof AuthenticatedSkorRoute
  '/viewer': typeof AuthenticatedViewerRoute
  '/vmix': typeof AuthenticatedVmixRoute
  '/vmix/leaderboard': typeof VmixLeaderboardRoute
  '/vmix/nowreading': typeof VmixNowreadingRoute
  '/vmix/skor': typeof VmixSkorRoute
  '/vmix/varwarning': typeof VmixVarwarningRoute
  '/api/public/bootstrap-admin': typeof ApiPublicBootstrapAdminRoute
  '/api/public/bootstrap-juri-dummy': typeof ApiPublicBootstrapJuriDummyRoute
  '/api/public/keberatan': typeof ApiPublicKeberatanRoute
  '/api/public/live.json': typeof ApiPublicLiveDotjsonRoute
  '/api/public/nowreading.xml': typeof ApiPublicNowreadingDotxmlRoute
  '/api/public/skor.json': typeof ApiPublicSkorDotjsonRoute
  '/api/public/skor.xml': typeof ApiPublicSkorDotxmlRoute
  '/api/public/vmix/leaderboard.html': typeof ApiPublicVmixLeaderboardDothtmlRoute
  '/api/public/vmix/nowreading.html': typeof ApiPublicVmixNowreadingDothtmlRoute
  '/api/public/vmix/skor.html': typeof ApiPublicVmixSkorDothtmlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/daftar': typeof DaftarRoute
  '/keberatan': typeof KeberatanRoute
  '/live': typeof LiveRoute
  '/posisi': typeof PosisiRoute
  '/ranking': typeof RankingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/inspektur': typeof AuthenticatedInspekturRoute
  '/_authenticated/inspektur-var': typeof AuthenticatedInspekturVarRoute
  '/_authenticated/operator': typeof AuthenticatedOperatorRoute
  '/_authenticated/skor': typeof AuthenticatedSkorRoute
  '/_authenticated/viewer': typeof AuthenticatedViewerRoute
  '/_authenticated/vmix': typeof AuthenticatedVmixRoute
  '/vmix/leaderboard': typeof VmixLeaderboardRoute
  '/vmix/nowreading': typeof VmixNowreadingRoute
  '/vmix/skor': typeof VmixSkorRoute
  '/vmix/varwarning': typeof VmixVarwarningRoute
  '/api/public/bootstrap-admin': typeof ApiPublicBootstrapAdminRoute
  '/api/public/bootstrap-juri-dummy': typeof ApiPublicBootstrapJuriDummyRoute
  '/api/public/keberatan': typeof ApiPublicKeberatanRoute
  '/api/public/live.json': typeof ApiPublicLiveDotjsonRoute
  '/api/public/nowreading.xml': typeof ApiPublicNowreadingDotxmlRoute
  '/api/public/skor.json': typeof ApiPublicSkorDotjsonRoute
  '/api/public/skor.xml': typeof ApiPublicSkorDotxmlRoute
  '/api/public/vmix/leaderboard.html': typeof ApiPublicVmixLeaderboardDothtmlRoute
  '/api/public/vmix/nowreading.html': typeof ApiPublicVmixNowreadingDothtmlRoute
  '/api/public/vmix/skor.html': typeof ApiPublicVmixSkorDothtmlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/daftar'
    | '/keberatan'
    | '/live'
    | '/posisi'
    | '/ranking'
    | '/sitemap.xml'
    | '/dashboard'
    | '/inspektur'
    | '/inspektur-var'
    | '/operator'
    | '/skor'
    | '/viewer'
    | '/vmix'
    | '/vmix/leaderboard'
    | '/vmix/nowreading'
    | '/vmix/skor'
    | '/vmix/varwarning'
    | '/api/public/bootstrap-admin'
    | '/api/public/bootstrap-juri-dummy'
    | '/api/public/keberatan'
    | '/api/public/live.json'
    | '/api/public/nowreading.xml'
    | '/api/public/skor.json'
    | '/api/public/skor.xml'
    | '/api/public/vmix/leaderboard.html'
    | '/api/public/vmix/nowreading.html'
    | '/api/public/vmix/skor.html'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/daftar'
    | '/keberatan'
    | '/live'
    | '/posisi'
    | '/ranking'
    | '/sitemap.xml'
    | '/dashboard'
    | '/inspektur'
    | '/inspektur-var'
    | '/operator'
    | '/skor'
    | '/viewer'
    | '/vmix'
    | '/vmix/leaderboard'
    | '/vmix/nowreading'
    | '/vmix/skor'
    | '/vmix/varwarning'
    | '/api/public/bootstrap-admin'
    | '/api/public/bootstrap-juri-dummy'
    | '/api/public/keberatan'
    | '/api/public/live.json'
    | '/api/public/nowreading.xml'
    | '/api/public/skor.json'
    | '/api/public/skor.xml'
    | '/api/public/vmix/leaderboard.html'
    | '/api/public/vmix/nowreading.html'
    | '/api/public/vmix/skor.html'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/daftar'
    | '/keberatan'
    | '/live'
    | '/posisi'
    | '/ranking'
    | '/sitemap.xml'
    | '/_authenticated/dashboard'
    | '/_authenticated/inspektur'
    | '/_authenticated/inspektur-var'
    | '/_authenticated/operator'
    | '/_authenticated/skor'
    | '/_authenticated/viewer'
    | '/_authenticated/vmix'
    | '/vmix/leaderboard'
    | '/vmix/nowreading'
    | '/vmix/skor'
    | '/vmix/varwarning'
    | '/api/public/bootstrap-admin'
    | '/api/public/bootstrap-juri-dummy'
    | '/api/public/keberatan'
    | '/api/public/live.json'
    | '/api/public/nowreading.xml'
    | '/api/public/skor.json'
    | '/api/public/skor.xml'
    | '/api/public/vmix/leaderboard.html'
    | '/api/public/vmix/nowreading.html'
    | '/api/public/vmix/skor.html'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  DaftarRoute: typeof DaftarRoute
  KeberatanRoute: typeof KeberatanRoute
  LiveRoute: typeof LiveRoute
  PosisiRoute: typeof PosisiRoute
  RankingRoute: typeof RankingRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  VmixLeaderboardRoute: typeof VmixLeaderboardRoute
  VmixNowreadingRoute: typeof VmixNowreadingRoute
  VmixSkorRoute: typeof VmixSkorRoute
  VmixVarwarningRoute: typeof VmixVarwarningRoute
  ApiPublicBootstrapAdminRoute: typeof ApiPublicBootstrapAdminRoute
  ApiPublicBootstrapJuriDummyRoute: typeof ApiPublicBootstrapJuriDummyRoute
  ApiPublicKeberatanRoute: typeof ApiPublicKeberatanRoute
  ApiPublicLiveDotjsonRoute: typeof ApiPublicLiveDotjsonRoute
  ApiPublicNowreadingDotxmlRoute: typeof ApiPublicNowreadingDotxmlRoute
  ApiPublicSkorDotjsonRoute: typeof ApiPublicSkorDotjsonRoute
  ApiPublicSkorDotxmlRoute: typeof ApiPublicSkorDotxmlRoute
  ApiPublicVmixLeaderboardDothtmlRoute: typeof ApiPublicVmixLeaderboardDothtmlRoute
  ApiPublicVmixNowreadingDothtmlRoute: typeof ApiPublicVmixNowreadingDothtmlRoute
  ApiPublicVmixSkorDothtmlRoute: typeof ApiPublicVmixSkorDothtmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ranking': {
      id: '/ranking'
      path: '/ranking'
      fullPath: '/ranking'
      preLoaderRoute: typeof RankingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posisi': {
      id: '/posisi'
      path: '/posisi'
      fullPath: '/posisi'
      preLoaderRoute: typeof PosisiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/keberatan': {
      id: '/keberatan'
      path: '/keberatan'
      fullPath: '/keberatan'
      preLoaderRoute: typeof KeberatanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daftar': {
      id: '/daftar'
      path: '/daftar'
      fullPath: '/daftar'
      preLoaderRoute: typeof DaftarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vmix/varwarning': {
      id: '/vmix/varwarning'
      path: '/vmix/varwarning'
      fullPath: '/vmix/varwarning'
      preLoaderRoute: typeof VmixVarwarningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vmix/skor': {
      id: '/vmix/skor'
      path: '/vmix/skor'
      fullPath: '/vmix/skor'
      preLoaderRoute: typeof VmixSkorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vmix/nowreading': {
      id: '/vmix/nowreading'
      path: '/vmix/nowreading'
      fullPath: '/vmix/nowreading'
      preLoaderRoute: typeof VmixNowreadingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vmix/leaderboard': {
      id: '/vmix/leaderboard'
      path: '/vmix/leaderboard'
      fullPath: '/vmix/leaderboard'
      preLoaderRoute: typeof VmixLeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/vmix': {
      id: '/_authenticated/vmix'
      path: '/vmix'
      fullPath: '/vmix'
      preLoaderRoute: typeof AuthenticatedVmixRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/viewer': {
      id: '/_authenticated/viewer'
      path: '/viewer'
      fullPath: '/viewer'
      preLoaderRoute: typeof AuthenticatedViewerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/skor': {
      id: '/_authenticated/skor'
      path: '/skor'
      fullPath: '/skor'
      preLoaderRoute: typeof AuthenticatedSkorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/operator': {
      id: '/_authenticated/operator'
      path: '/operator'
      fullPath: '/operator'
      preLoaderRoute: typeof AuthenticatedOperatorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inspektur-var': {
      id: '/_authenticated/inspektur-var'
      path: '/inspektur-var'
      fullPath: '/inspektur-var'
      preLoaderRoute: typeof AuthenticatedInspekturVarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inspektur': {
      id: '/_authenticated/inspektur'
      path: '/inspektur'
      fullPath: '/inspektur'
      preLoaderRoute: typeof AuthenticatedInspekturRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/skor.xml': {
      id: '/api/public/skor.xml'
      path: '/api/public/skor.xml'
      fullPath: '/api/public/skor.xml'
      preLoaderRoute: typeof ApiPublicSkorDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/skor.json': {
      id: '/api/public/skor.json'
      path: '/api/public/skor.json'
      fullPath: '/api/public/skor.json'
      preLoaderRoute: typeof ApiPublicSkorDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/nowreading.xml': {
      id: '/api/public/nowreading.xml'
      path: '/api/public/nowreading.xml'
      fullPath: '/api/public/nowreading.xml'
      preLoaderRoute: typeof ApiPublicNowreadingDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/live.json': {
      id: '/api/public/live.json'
      path: '/api/public/live.json'
      fullPath: '/api/public/live.json'
      preLoaderRoute: typeof ApiPublicLiveDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/keberatan': {
      id: '/api/public/keberatan'
      path: '/api/public/keberatan'
      fullPath: '/api/public/keberatan'
      preLoaderRoute: typeof ApiPublicKeberatanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bootstrap-juri-dummy': {
      id: '/api/public/bootstrap-juri-dummy'
      path: '/api/public/bootstrap-juri-dummy'
      fullPath: '/api/public/bootstrap-juri-dummy'
      preLoaderRoute: typeof ApiPublicBootstrapJuriDummyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bootstrap-admin': {
      id: '/api/public/bootstrap-admin'
      path: '/api/public/bootstrap-admin'
      fullPath: '/api/public/bootstrap-admin'
      preLoaderRoute: typeof ApiPublicBootstrapAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/vmix/skor.html': {
      id: '/api/public/vmix/skor.html'
      path: '/api/public/vmix/skor.html'
      fullPath: '/api/public/vmix/skor.html'
      preLoaderRoute: typeof ApiPublicVmixSkorDothtmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/vmix/nowreading.html': {
      id: '/api/public/vmix/nowreading.html'
      path: '/api/public/vmix/nowreading.html'
      fullPath: '/api/public/vmix/nowreading.html'
      preLoaderRoute: typeof ApiPublicVmixNowreadingDothtmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/vmix/leaderboard.html': {
      id: '/api/public/vmix/leaderboard.html'
      path: '/api/public/vmix/leaderboard.html'
      fullPath: '/api/public/vmix/leaderboard.html'
      preLoaderRoute: typeof ApiPublicVmixLeaderboardDothtmlRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedInspekturRoute: typeof AuthenticatedInspekturRoute
  AuthenticatedInspekturVarRoute: typeof AuthenticatedInspekturVarRoute
  AuthenticatedOperatorRoute: typeof AuthenticatedOperatorRoute
  AuthenticatedSkorRoute: typeof AuthenticatedSkorRoute
  AuthenticatedViewerRoute: typeof AuthenticatedViewerRoute
  AuthenticatedVmixRoute: typeof AuthenticatedVmixRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedInspekturRoute: AuthenticatedInspekturRoute,
  AuthenticatedInspekturVarRoute: AuthenticatedInspekturVarRoute,
  AuthenticatedOperatorRoute: AuthenticatedOperatorRoute,
  AuthenticatedSkorRoute: AuthenticatedSkorRoute,
  AuthenticatedViewerRoute: AuthenticatedViewerRoute,
  AuthenticatedVmixRoute: AuthenticatedVmixRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  DaftarRoute: DaftarRoute,
  KeberatanRoute: KeberatanRoute,
  LiveRoute: LiveRoute,
  PosisiRoute: PosisiRoute,
  RankingRoute: RankingRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  VmixLeaderboardRoute: VmixLeaderboardRoute,
  VmixNowreadingRoute: VmixNowreadingRoute,
  VmixSkorRoute: VmixSkorRoute,
  VmixVarwarningRoute: VmixVarwarningRoute,
  ApiPublicBootstrapAdminRoute: ApiPublicBootstrapAdminRoute,
  ApiPublicBootstrapJuriDummyRoute: ApiPublicBootstrapJuriDummyRoute,
  ApiPublicKeberatanRoute: ApiPublicKeberatanRoute,
  ApiPublicLiveDotjsonRoute: ApiPublicLiveDotjsonRoute,
  ApiPublicNowreadingDotxmlRoute: ApiPublicNowreadingDotxmlRoute,
  ApiPublicSkorDotjsonRoute: ApiPublicSkorDotjsonRoute,
  ApiPublicSkorDotxmlRoute: ApiPublicSkorDotxmlRoute,
  ApiPublicVmixLeaderboardDothtmlRoute: ApiPublicVmixLeaderboardDothtmlRoute,
  ApiPublicVmixNowreadingDothtmlRoute: ApiPublicVmixNowreadingDothtmlRoute,
  ApiPublicVmixSkorDothtmlRoute: ApiPublicVmixSkorDothtmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
